### ISSUE TITLE
Menu screen flickers

### ISSUE THREAD

**Issue by Cralex** [rs90-randomsjunk/gnuboy_rs90#1]
All lines of text on the emulator menu flickers with horizontal black lines going through it. See short clip: https://www.dropbox.com/s/t8hvreasdnsybja/gnuboy.MOV?dl=0

**Comment by Cralex** [comment]
I see you fixed this already :)

**Comment by gameblabla** [comment]
@Cralex Yeah, but i uploaded a build after that which crashed.... then i quickly uploaded another build which fixed both issues. So we should be okay now.
