### ISSUE TITLE
Start + Select Menu Shortcut Prevents Native Saves in Link’s Awakening

### ISSUE THREAD

**Issue by Cralex** [rs90-randomsjunk/gnuboy_rs90#2]
From what I can tell, the menu is called with either L, R, or Start + Select. Because the native save menu in Link’s Awakening and Link’s Awakening DX is called with A + B + Start + Select, it isn’t possible to save natively in these games without triggering the emulator menu. (Or getting a game over and saving from there.)

**Comment by gameblabla** [comment]
That's very unusual, i guess we could disable the fact that Start + Select triggers the menu.

**Comment by Cralex** [comment]
Yeah. I mean, I appreciate how quiet it is as a menu shortcut. (The L and R buttons on this thing click loud!) But it does prevent save warping and such with Link’s Awakening.

**Comment by gameblabla** [comment]
Fixed as of https://github.com/rs90-randomsjunk/gnuboy_rs90/commit/74013ce54c2f756a8f5bbc23be15b95a38d2880c. I also updated the OPK build. I mean other than using L or R buttons, i don't know how we could go around this given that these games use all 4 buttons.
